---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeuler-patch-tracking-db-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd
